

spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/property-management

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    username: waaprogectresetpass@gmail.com
    password: Test@123Waa
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
  multipart.max-file-size: 5MB
  multipart.max-request-size: 5MB

  server:
    port: 8080
cloud:
  aws.credentials.access-key: AKIAZBNRKNRLEK4HJIAZ
  aws.credentials.secret-key: 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
  aws.region.static: us-east-1
  aws.stack.auto: false


